# Generated by Django 3.2.8 on 2021-10-10 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('method', '0001_initial'),
        ('store', '0002_book_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='genres',
            field=models.ManyToManyField(to='method.Genre'),
        ),
    ]
