# Generated by Django 3.2.8 on 2021-10-12 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_book_autor_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='autor_name',
            new_name='author_name',
        ),
    ]
