# Generated by Django 3.2.8 on 2021-10-16 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('method', '0001_initial'),
        ('store', '0006_auto_20211016_0933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='genres',
            field=models.ManyToManyField(blank=True, to='method.Genre'),
        ),
    ]
